### ISSUE TITLE
自身のパスワードを変更しようとした際に、入力間違いをしてしまう。

### ISSUE THREAD

**Issue by shizm** [WIT-SYS2/claude#49]
プロフィール変更画面について、

* 名前
* メールアドレス
* 新しいパスワード
* 新しいパスワード（確認）
* 現在のパスワード

となっているが、「パスワード（確認）」と「現在のパスワード」の間隔が狭いため、注意しないと利用者が

* 現在のパスワード
* 新しいパスワード
* 新しいパスワード（確認）

という並び順と勘違いして入力してしまう。

項目間に`<hr>`で区切り線を入れるなどしてグルーピングが分かるようにした方が良い

![profile](https://f.cloud.github.com/assets/85830/861551/fa819982-f5d3-11e2-9e46-f0b5be45a4d5.png)

**Comment by maki-tetsu** [comment]
パスワード変更機能は master では削除されたのでこの Issue は終了します。
