### ISSUE TITLE
一覧のタブが効いてないですね

### ISSUE THREAD

**Issue by hashima0** [WIT-SYS2/claude#70]
故に「すべて」に遷移できません。

**Comment by maki-tetsu** [comment]
development 環境では再現しませんね。
master で再現しません。

**Comment by maki-tetsu** [comment]
development で再現しないのでもしかしたらと思いますが、これ rails_12factor の影響と思われます。
#71 でも挙げていますが、rails_12factor は Heroku 環境で動作させるためのライブラリのようで、assets の扱いも異なるようです。試しにソースを確認したのですが、AWS 上の環境では Ajax リクエストの発行先の URL から /claude が消えており 404 not found が返却されています。
rails_12factor が原因かまでは分かりませんが、おそらく原因の一つかと思います。

**Comment by maki-tetsu** [comment]
原因は #74 でした。
重複しますが、クローズせずに残しておきます。

**Comment by maki-tetsu** [comment]
AWS環境をサーバルートで動作するように切り替えたところ正しく動作することを確認できました。
動作確認で問題なければこの Issue は終了してもらえますか？ > @hashima0 
本質的な対応については移行プロジェクトからは除外し、 #74 での対応にしたいと思います。

**Comment by hashima0** [comment]
対応ありがとうございました。 > @maki-tetsu
